### ISSUE TITLE
pyffstream: error: input files must be files or directories

### ISSUE THREAD

**Issue by l1tecoding** [GBeauregard/pyffstream#1]
pyffstream: error: input files must be files or directories

How to specify the file correctly?

**Comment by givanchick** [comment]
> Для файла необходимо указать его абсолютный путь или относительно текущего каталога. Это может быть проще, если вы `cd`сначала перейдете в каталог с файлом, который пытаетесь использовать.

That's right, I'm in this directory, but I get an error)

**pyffstream input_files "test.mp4"  --vbitrate 800k --x264 --height 864   -A 128k --protocol rtmp**

**Comment by GBeauregard** [comment]
> > Для файла необходимо указать его абсолютный путь или относительно текущего каталога. Это может быть проще, если вы `cd`сначала перейдете в каталог с файлом, который пытаетесь использовать.
> 
> That's right, I'm in this directory, but I get an error)
> 
> **pyffstream input_files "test.mp4" --vbitrate 800k --x264 --height 864 -A 128k --protocol rtmp**
You want this. You don't need to specify "input_files".
`pyffstream "test.mp4" --vbitrate 800k --x264 --height 864 -A 128k --protocol rtmp`

**Comment by givanchick** [comment]
pyffstream -i test.mp4 - i see info, yes

**Comment by givanchick** [comment]
> Вы хотите это. Вам не нужно указывать input_files. `pyffstream "test.mp4" --vbitrate 800k --x264 --height 864 -A 128k --protocol rtmp`

Thanks. Also Can I set metadata?
